
version: '2'

networks:
    main:

volumes:
    config:
        driver: local
    torrents:
        driver: local


services:
      private_rtorrent:
        image: wakemaster39/seedbox:private_rtorrent
        restart: always
        networks:
            - main
        ports:
            - "49161:49161"
            - "49161:49161/udp"
            - "6881:6881/udp"
        volumes:
            - config:/config
            - torrents:/torrents
services:
    frontend:
        image: wakemaster39/seedbox:frontend
        restart: always
        networks:
            - main
        ports:
            - "1500:80"
            - "443:443"
        volumes:
            - config:/config
        env_file:
            - config
